version: '3'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-llm-assistant
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs